[functions]
included_files = ["equipment/*.svg"]

[[redirects]]
from = "/api/icons"
to = "/.netlify/functions/icons"
status = 200

[[redirects]]
from = "/api/spellcheck-recipe"
to = "/.netlify/functions/spellcheck-recipe"
status = 200

[[redirects]]
from = "/api/export-meal-planner"
to = "/.netlify/functions/export-meal-planner"
status = 200

[[redirects]]
from = "/api/generate-meal-planner-metadata"
to = "/.netlify/functions/generate-meal-planner-metadata"
status = 200
